<a href="https://colab.research.google.com/github/ReanSchwarzer1/Notebooks/blob/master/GameOfLife.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import time       
from scipy.signal import convolve


##We use this to count the number of living neighbors each cell has

In [0]:
cells = np.array([[0, 0, 1, 0, 1], [0, 1, 0, 0, 1], [0, 1, 0, 0, 1], [0, 0, 1, 0, 1]], dtype=np.uint8)
print(cells)    

[[0 0 1 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 0 1 0 1]]


## For running Conway's game of life

In [0]:
def evolveCells(length, generations):
    current = np.random.randint(2, size=(length, length))
    next = np.empty_like(current)
    current[length//2, 1:(length-1)] = 1
    show_board(current)
    for _ in range(generations):
        advanceCells(current, next)
        current, next = next, current
        show_board(current)

In [0]:
def advanceCells(current, next):
    assert current.shape[0] == current.shape[1], \
           'Square universe should be expected in bounds of the matrix (world) i.e 4 rows and 5 columns'
    next[:] = 0
    count = convolve(current, cells, mode='same')
    next[(count == 3) | (count == 102) | (count == 103)] = 1

In [0]:
##### We need to change this whole block since we need the output in 0s and 1s

from IPython.display import clear_output, display_html
def show_board(board):
    nx, ny = board.shape
    table = '<table style="border-color: black; border-width: 5px;">\n'
    for y in range(ny-1, -1, -1):
        table += '<tr>'
        for x in range(0, nx):
            if board[x, y]:
                table += '<td style="background: black; border-color: white;"></td>'
            else:
                table += '<td style="border-color: white;"></td>'
        table += '</tr>\n'
    table += '</table>'
    display_html(table, raw=True)
    time.sleep(0.1)

## evolveCells() function has two parameters. Since, we need to display the 20th generation the second argument is 20

In [85]:
evolveCells(20, 20)