Note: This notebook is compiled from Kavin's and Saanvi Singh's solutions

*(Feel free to refer to the AI Intern Day 4 Jupyter notebook if you get stuck.)*

## Classes:

Create a class in Python to represent fractions. The internal representation contains two integers (the numerator and denominator). 

The functions in the class should include:
   * multiplication (a/b * c/d)
   * print the fraction (in the form a/b) (hint: use \__str__ function)
   * invert the fraction (a/b becomes b/a)

#### Example usage of this class:

frac = Fraction(3, 4) # Fraction 3/4

frac2 = Fraction(4, 3) # Fraction 4/3

frac.multiply(frac2)

print(frac)

frac.invert()

In [2]:
class Fraction():
    def __init__(self,n,d):
        self.num = n
        self.den = d
    def multiply(self, other):
        return((self.num*other.num)/(self.den*other.den))
    def __str__(self):
        return(str(self.num)+"/"+str(self.den))
    def invert(self):
        self.num, self.den = self.den, self.num

In [3]:
frac = Fraction(3,4)
frac2 = Fraction(2,5)
print("Fraction 1: {} || Fraction 2: {}".format(frac.__str__(),frac2.__str__()))
print("Mutilplied Value:")
mul = frac.multiply(frac2)
print(mul)
frac.invert()
print("After Inverting:")
print(frac)

Fraction 1: 3/4 || Fraction 2: 2/5
Mutilplied Value:
0.3
After Inverting:
4/3


## Numpy:

In [5]:
# Get a list of integers as input from the user and convert it into a numpy array.
import numpy as np
lst = list(map(int,input().split()))#[1,2,3,4,5,6,7,8]
arr=np.array(lst)
print(arr)

1 2 3 4 54
[ 1  2  3  4 54]


In [6]:
# Create an array of ones (all elements in the array is one) of shape (4, 5) [three rows and 5 columns]. 
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
'''
Given the following array,

X = [[2, 5],
    [1, 5],
    [0, 7]]
    
Write numpy slicing code to get the following as output:

1. [2, 1, 0]
2. [1, 5]
3. 7
4. [2, 7, 0]  (hint, use a list of indices)

'''
X = [[2, 5],[1, 5],[0, 7]]
X = np.array(X)
print("1.",X[:,0])
print("2.",X[1])
print("3.",X[-1,1])
row_index = [0,2,2] #Row and col pair for accessing the specific values (Fancy Indexing)
col_index = [0,1,0]
print("4.",X[row_index,col_index])

1. [2 1 0]
2. [1 5]
3. 7
4. [2 7 0]


In [8]:
# Create a numpy array and print its shape, dimensions, size and datatype
arr = np.random.randint(10, size=(10))
arr = arr.reshape(2,5)
print("Dim: ", arr.ndim)
print("Shape:", arr.shape)
print("Size: ", arr.size)

Dim:  2
Shape: (2, 5)
Size:  10


In [9]:
# Create a copy of a numpy array using .copy(), change the copy's value and print both arrays

x=np.ones((4,6))
y=x.copy()

y[0,:]=0

print(x)

print(y)


[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [10]:
# Create a numpy array of size 15 and print all possible reshaping.
factors=[]
for i in range(1,16):
    if 15%i==0:
        factors.append(i)
#print(factors)
a=np.arange(15)
for i in factors:
    for j in factors:
        if i*j==15:
            a=a.reshape((i,j))
            print(a.shape)
            print(a)
            print()

(1, 15)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]

(3, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

(5, 3)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

(15, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]]



In [11]:
# Create a random array of shape (3, 4) and find the maximum in it
# hint : np.random.randint(0, 100, size=(3, 4))
X=np.random.randint(0,100,size=(3,4))
print(X)

print(np.max(X))

[[43 80 34 38]
 [47 94 61 16]
 [65 97  9 85]]
97


In [12]:
# Sort the following array:
# x = np.array([2, 1, 4, 3, 5])
x = np.array([2,1,4,3,5])
print(np.sort(x))


[1 2 3 4 5]


In [13]:
# find the maximum element in each column of the folling array

a = np.array([[1,2,4,7],
              [9,88,6,45],
              [9,76,3,4]])
a.max(axis=0)



array([ 9, 88,  6, 45])

In [14]:
# find the index of the maximum element in each column in the folling array
# a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
Array4 = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
print(np.argmax(Array4,axis=0))

[1 1 1 1]


In [15]:
# Try adding an array of shape (3,4) and another array of shape (3,1)
a1 = np.random.randint(0, 100, size=(3, 4))
a2 = np.random.randint(0, 100, size=(3, 1))
print("Matrix 1: \n",a1)
print("Matrix 2: \n",a2)
a1+a2

Matrix 1: 
 [[24 50  7 88]
 [ 8 41 29 86]
 [42 83 57 29]]
Matrix 2: 
 [[19]
 [56]
 [70]]


array([[ 43,  69,  26, 107],
       [ 64,  97,  85, 142],
       [112, 153, 127,  99]])

In [16]:
# Try adding an array of shape (5,) and (,5)
b1 = np.random.randint(0, 100, size=(5))
b2 = np.random.randint(0, 100, size=(5))
print(b1)
print(b2)
b1+b2

[13 85 12 91 11]
[60 98 89 16 55]


array([ 73, 183, 101, 107,  66])

In [17]:
# Try adding two arrays of shape (3,3) and (2,2) each

try:
    M=np.ones((3,3))
    N=np.ones((2,2))
    print(M+N)
except:
    print("Not posible to add two arrays of shape (3,3) and (2,2)")

Not posible to add two arrays of shape (3,3) and (2,2)
